name: Test suite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    - name: Setup udev device correctly
      run: |
        sudo modprobe -i uinput
        echo KERNEL==\"uinput\", SUBSYSTEM==\"misc\" GROUP=\"docker\", MODE:=\"0666\" | sudo tee /etc/udev/rules.d/99-$USER.rules
        echo KERNEL==\"event[0-9]*\", SUBSYSTEM==\"input\" GROUP=\"docker\", MODE:=\"0666\" | sudo tee -a /etc/udev/rules.d/99-$USER.rules
        cat /etc/udev/rules.d/99-$USER.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger
    - name: Install dependencies
      run: |
        pip install --disable-pip-version-check -e .[dev]
    - name: Linting
      run: |
        scripts/lint.sh
    - name: Build package
      run: |
        python -m build
        twine check dist/*
    - name: Tests
      run: ward
